name: CI linux

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: CI on Linux

    runs-on: ubuntu-18.04

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install toolchain
      uses: ada-actions/toolchain@ce2021
      with:
        distrib: community
    
    - name: Build release
      run: >
        gprbuild -P vaniton.gpr -XBUILD=RELEASE -j0
    
    - name: Upload binaries
      uses: actions/upload-artifact@v2
      with:
        name: vaniton-bin-linux.zip
        path: |
          bin/vaniton
          bin/mnemonic2address
          README.md
          LICENSE.txt
